### ISSUE TITLE
django-admin-tools base template conflict with su base_site.html

### ISSUE THREAD

**Issue by shtalinberg** [adamcharnock/django-su#59]
https://github.com/django-admin-tools/django-admin-tools/blob/master/admin_tools/menu/templates/admin/base_site.html

```
INSTALLED_APPS = (
    'django_su',

    'admin_tools',
    'admin_tools.theming',
    'admin_tools.menu',
    'admin_tools.dashboard',

    'django.contrib.auth',
    ........
)
```

**Comment by adamcharnock** [comment]
Hi @shtalinberg, thank you for raising this. From what I recall, we need to extend `admin/base_site.html` in order to modify the base admin template.

It seems this was added in #54, and is non-critical to django-su's operation. Therefore placing `django_su` after `admin_tools.*` in `INSTALLED_APPS` should cause django-su's customised `admin/base_site.html` to be ignored.

I'm going to close this now because I don't think it is a common problem and I'm not aware of a work around. 

If this becomes a problem for others please leave a comment below. I am subscribed to this issue so will receive notifications.

**Comment by hwkns** [comment]
For what it's worth, I also ran into this when trying out https://github.com/fabiocaccamo/django-admin-interface.

**Comment by hwkns** [comment]
Yes, @adamcharnock, that workaround was effective for getting the other package working.
