### ISSUE TITLE
Usage with custom AUTH_USER_MODEL

### ISSUE THREAD

**Issue by PetrDlouhy** [adamcharnock/django-su#62]
The `django-su` application doesn't work out of the box. It requires setting of template paths. Please mention this in the README for future developers. My code looks like:

```python
@admin.register(models.UserProfile)
class UserProfileAdmin(UserAdmin):
    change_form_template = "admin/auth/user/change_form.html"
    change_list_template = "admin/auth/user/change_list.html"
```

**Comment by adamcharnock** [comment]
Thank you @PetrDlouhy! I'm guessing this is caused by [this line](https://github.com/django/django/blob/master/django/contrib/admin/options.py#L1164) in Django's `ModelAdmin` class. Specifically, a custom user model will have a different `app_label` (or even a different `model_name`) and therefore the auto-determined template will not be what django-su expects. I'll see what I can do.

**Comment by adamcharnock** [comment]
Documented! Thanks again for flagging this up @PetrDlouhy 👍
